import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from openpyxl import load_workbook


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

EXCEL_DIR = PROJECT_ROOT / "Excel"
OUTPUT_DIR = PROJECT_ROOT / "outputs"

OUTPUT_DIR.mkdir(exist_ok=True)


# ============================================================
# 2. FIND EXCEL FILE
# ============================================================

excel_files = list(EXCEL_DIR.glob("*.xlsx"))

if not excel_files:
    raise FileNotFoundError(
        f"No Excel file found in: {EXCEL_DIR}"
    )

excel_file = excel_files[0]

print(f"Reading Excel file:")
print(excel_file)


# ============================================================
# 3. READ EXCEL SHEETS
# ============================================================

wb = load_workbook(
    excel_file,
    data_only=True
)

print("\nSheets:")
print(wb.sheetnames)


# ============================================================
# 4. HELPER FUNCTION
# ============================================================

def get_value(sheet_name, cell):

    ws = wb[sheet_name]

    return ws[cell].value


# ============================================================
# 5. READ DASHBOARD KPIs
# ============================================================

aop_demand = get_value(
    "11_Management_Dashboard",
    "A5"
)

forecast_demand = get_value(
    "11_Management_Dashboard",
    "B5"
)

forecast_accuracy = get_value(
    "11_Management_Dashboard",
    "C5"
)

products_below_rop = get_value(
    "11_Management_Dashboard",
    "D5"
)

current_inventory = get_value(
    "11_Management_Dashboard",
    "E5"
)

recommended_order = get_value(
    "11_Management_Dashboard",
    "F5"
)

aop_variance = get_value(
    "11_Management_Dashboard",
    "G5"
)


# ============================================================
# 6. READ AOP / ACTUAL DEMAND
# ============================================================

aop_actual_sheet = wb["10_AOP_Variance"]

actual_demand = aop_actual_sheet["B4"].value


# ============================================================
# 7. READ INVENTORY ANALYSIS
# ============================================================

inventory_sheet = wb["06_Inventory_Analysis"]

inventory_data = []

for row in range(14, 64):

    sku = inventory_sheet[f"A{row}"].value
    current = inventory_sheet[f"B{row}"].value
    rop = inventory_sheet[f"E{row}"].value
    gap = inventory_sheet[f"F{row}"].value
    status = inventory_sheet[f"H{row}"].value
    order = inventory_sheet[f"I{row}"].value

    if sku is not None:

        inventory_data.append({
            "SKU_ID": sku,
            "Current Inventory": current,
            "Reorder Point": rop,
            "Inventory Gap": gap,
            "Recommended Order": order,
            "Status": status
        })


inventory_df = pd.DataFrame(inventory_data)


# ============================================================
# 8. TOP 5 SKUs BY RECOMMENDED ORDER
# ============================================================

top5 = (
    inventory_df
    .sort_values(
        "Recommended Order",
        ascending=False
    )
    .head(5)
)


# ============================================================
# 9. FORMAT FUNCTION
# ============================================================

def number(value):

    if value is None:
        return "N/A"

    return f"{value:,.0f}".replace(",", ".")


def decimal(value):

    if value is None:
        return "N/A"

    return f"{value:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")


def percent(value):

    if value is None:
        return "N/A"

    # Excel stores 98.78% as 0.9878
    if abs(value) < 1:
        value = value * 100

    return f"{value:.2f}%".replace(".", ",")


# ============================================================
# 10. CREATE FIGURE
# ============================================================

fig = plt.figure(
    figsize=(18, 12),
    dpi=150
)

fig.patch.set_facecolor("white")


# ============================================================
# 11. TITLE
# ============================================================

fig.suptitle(
    "Demand & Supply Planning Analytics",
    fontsize=24,
    fontweight="bold",
    y=0.98
)

fig.text(
    0.5,
    0.945,
    "Key Results from Excel File — Auto-Generated by Python",
    ha="center",
    fontsize=13
)


# ============================================================
# 12. KPI CARDS
# ============================================================

kpis = [
    ("AOP Demand", number(aop_demand)),
    ("Forecast Demand", number(forecast_demand)),
    ("Forecast Accuracy", percent(forecast_accuracy)),
    ("Products Below ROP", number(products_below_rop)),
    ("Current Inventory", number(current_inventory)),
    ("Recommended Order", number(recommended_order)),
    ("AOP Variance", percent(aop_variance)),
]


for i, (label, value) in enumerate(kpis):

    x = 0.03 + i * 0.138

    ax = fig.add_axes([
        x,
        0.855,
        0.125,
        0.075
    ])

    ax.set_xticks([])
    ax.set_yticks([])

    for spine in ax.spines.values():
        spine.set_visible(True)

    ax.text(
        0.5,
        0.72,
        label,
        ha="center",
        va="center",
        fontsize=9,
        fontweight="bold"
    )

    ax.text(
        0.5,
        0.30,
        value,
        ha="center",
        va="center",
        fontsize=15,
        fontweight="bold"
    )


# ============================================================
# 13. CHART 1
# AOP vs FORECAST
# ============================================================

ax1 = fig.add_axes([
    0.05,
    0.60,
    0.27,
    0.20
])

ax1.bar(
    ["AOP Demand", "Forecast Demand"],
    [aop_demand, forecast_demand]
)

ax1.set_title(
    "AOP Demand vs Forecast Demand",
    fontweight="bold"
)

ax1.tick_params(axis="x", rotation=0)

for i, value in enumerate(
    [aop_demand, forecast_demand]
):

    ax1.text(
        i,
        value,
        number(value),
        ha="center",
        va="bottom",
        fontsize=9
    )


# ============================================================
# 14. CHART 2
# AOP vs ACTUAL
# ============================================================

ax2 = fig.add_axes([
    0.365,
    0.60,
    0.27,
    0.20
])

ax2.bar(
    ["AOP Demand", "Actual Demand"],
    [aop_demand, actual_demand]
)

ax2.set_title(
    "AOP Demand vs Actual Demand",
    fontweight="bold"
)

for i, value in enumerate(
    [aop_demand, actual_demand]
):

    ax2.text(
        i,
        value,
        number(value),
        ha="center",
        va="bottom",
        fontsize=9
    )


# ============================================================
# 15. CHART 3
# INVENTORY STATUS
# ============================================================

ok_count = (
    inventory_df["Status"]
    .eq("OK")
    .sum()
)

order_count = (
    inventory_df["Status"]
    .eq("ORDER")
    .sum()
)

ax3 = fig.add_axes([
    0.68,
    0.60,
    0.27,
    0.20
])

ax3.bar(
    ["OK", "ORDER"],
    [ok_count, order_count]
)

ax3.set_title(
    "Inventory Status by SKU",
    fontweight="bold"
)

for i, value in enumerate(
    [ok_count, order_count]
):

    ax3.text(
        i,
        value,
        str(value),
        ha="center",
        va="bottom",
        fontsize=10,
        fontweight="bold"
    )


# ============================================================
# 16. DEMAND SUMMARY
# ============================================================

ax4 = fig.add_axes([
    0.05,
    0.34,
    0.27,
    0.18
])

ax4.axis("off")

demand_text = (
    "DEMAND OVERVIEW\n\n"
    f"AOP Demand              {number(aop_demand)}\n"
    f"Forecast Demand         {number(forecast_demand)}\n"
    f"Actual Demand           {number(actual_demand)}\n"
    f"Forecast Accuracy       {percent(forecast_accuracy)}\n"
    f"AOP Variance            {percent(aop_variance)}"
)

ax4.text(
    0,
    1,
    demand_text,
    va="top",
    fontsize=11,
    linespacing=1.8
)


# ============================================================
# 17. INVENTORY SUMMARY
# ============================================================

ax5 = fig.add_axes([
    0.365,
    0.34,
    0.27,
    0.18
])

ax5.axis("off")

inventory_text = (
    "INVENTORY OVERVIEW\n\n"
    f"Current Inventory       {number(current_inventory)}\n"
    f"Recommended Order      {number(recommended_order)}\n"
    f"Products Below ROP     {number(products_below_rop)}\n"
    f"OK SKUs                {ok_count}\n"
    f"ORDER SKUs             {order_count}"
)

ax5.text(
    0,
    1,
    inventory_text,
    va="top",
    fontsize=11,
    linespacing=1.8
)


# ============================================================
# 18. TOP 5 SKU TABLE
# ============================================================

ax6 = fig.add_axes([
    0.68,
    0.32,
    0.27,
    0.21
])

ax6.axis("off")

table_data = []

for _, row in top5.iterrows():

    table_data.append([
        row["SKU_ID"],
        number(row["Current Inventory"]),
        decimal(row["Reorder Point"]),
        decimal(row["Recommended Order"])
    ])


table = ax6.table(
    cellText=table_data,
    colLabels=[
        "SKU",
        "Inventory",
        "ROP",
        "Recommended Order"
    ],
    loc="center",
    cellLoc="center"
)

table.auto_set_font_size(False)
table.set_fontsize(8)
table.scale(1, 1.7)

ax6.set_title(
    "Top 5 SKUs by Recommended Order",
    fontweight="bold",
    pad=10
)


# ============================================================
# 19. KEY INSIGHTS
# ============================================================

ax7 = fig.add_axes([
    0.05,
    0.07,
    0.43,
    0.20
])

ax7.axis("off")

insights = [
    f"• Forecast accuracy: {percent(forecast_accuracy)}",
    f"• {number(products_below_rop)} SKUs are below ROP.",
    f"• Recommended order: {number(recommended_order)} units.",
    f"• Actual demand: {number(actual_demand)} units.",
    f"• AOP variance: {percent(aop_variance)}.",
    f"• {order_count} SKUs currently require ordering."
]

ax7.text(
    0,
    1,
    "KEY INSIGHTS\n\n" + "\n".join(insights),
    va="top",
    fontsize=11,
    linespacing=1.7
)


# ============================================================
# 20. NEXT STEPS
# ============================================================

ax8 = fig.add_axes([
    0.52,
    0.07,
    0.43,
    0.20
])

ax8.axis("off")

next_steps = [
    "1. Review recommended orders.",
    "2. Investigate SKUs with largest inventory gaps.",
    "3. Monitor forecast accuracy.",
    "4. Check supply continuity for critical SKUs.",
    "5. Update planning assumptions regularly."
]

ax8.text(
    0,
    1,
    "NEXT STEPS\n\n" + "\n".join(next_steps),
    va="top",
    fontsize=11,
    linespacing=1.7
)


# ============================================================
# 21. SAVE IMAGE
# ============================================================

output_file = (
    OUTPUT_DIR /
    "management_dashboard_python.png"
)

plt.savefig(
    output_file,
    dpi=200,
    bbox_inches="tight"
)

plt.close()


# ============================================================
# 22. PRINT RESULTS
# ============================================================

print("\n" + "=" * 80)
print("IMAGE CREATED SUCCESSFULLY")
print("=" * 80)

print(f"\nExcel:")
print(excel_file)

print(f"\nOutput image:")
print(output_file)

print("\nKey results:")
print(f"AOP Demand:          {number(aop_demand)}")
print(f"Forecast Demand:     {number(forecast_demand)}")
print(f"Actual Demand:       {number(actual_demand)}")
print(f"Forecast Accuracy:   {percent(forecast_accuracy)}")
print(f"Below ROP:            {number(products_below_rop)}")
print(f"Current Inventory:   {number(current_inventory)}")
print(f"Recommended Order:   {number(recommended_order)}")
print(f"AOP Variance:         {percent(aop_variance)}")

print("\nDone.")